name: Docker Deployment
on:
  push:
    tags:
      - v3*
    # branches:
    #   - main
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push to github packages
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: ${{ github.event.repository.name }} # optional, defaults to repository name
            # tags: v1, latest # If remove will use tag name
            registry: ghcr.io # optional, defaults to ghcr.io
            #dockerfile: Dockerfile
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}