name: 'deployment'
on:
    push:
        tags:
            - '*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
    build-production:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Setup Node.js version 18.x
            uses: actions/setup-node@v3
            with:
              node-version: '18.x'
              cache: 'npm'
          - name: Install dependencies
            run: npm ci

          - name: Run build script
            run: npm run build

          - name: Upload build artifact
            #TOPIC: Artifact https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
            uses: actions/upload-artifact@v3
            with:
              name: dist-stage # Name of the artifact to upload
              path: dist # Directory that contains the files and subdirectories to upload
    deploy-to-production:
        needs: build-production
        runs-on: ubuntu-latest
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v3
              with:
                name: dist-stage # Name of the artifact to download
                #path: dist # Directory to download the artifact to
            - run: ls -la
