name: 'CI'
on:
  push:
    branches:
      - main

# NOTED: Parameter for setting up github action by specifying the working directory
# defaults:
#   run:
#     working-directory: ./frontend

jobs:
  lint-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js version 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        
      - name: Run format code
        run: npm run format
