name: 'CI'
on:
  push:
    branches:
      - main

# NOTED: Parameter for setting up github action by specifying the working directory
# defaults:
#   run:
#     working-directory: ./frontend

jobs:
  lint-job:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js version 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run format code
        run: npm run format

  unit-test-job:
    runs-on: self-hosted
    needs: lint-job # NOTED: run lint-job before unit-test-job
    strategy: # NOTED: create matix for test multi ENV https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x, 16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Test on ${{ matrix.os }} Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit test
        run: npm run test:unit


